исправление ошибок + , блоки на моб - Плитки товаров, попул…
htmlacademy-email/49149-play-html-1 pull request #7
Opened 2020-10-19 12:53 UTC by vigolajnen

…ярные курсы, ведущие курсов

2020-10-21 16:03 UTC, mailganer commented
Тег <style> не поддерживается во многох почтовых программах. А в остальных почтовых программах, где тег <style> поддерживается, не везде поддерживаются медиа-запросы. Надо переделать без медиа-запросов.

Посмотри пример https://codepen.io/Dako/pen/BazQybd

p.s.
Так же рекомендую вместо h2 использовать тег div

2020-10-21 16:29 UTC, mailganer requested changes
Тег <style> не поддерживается во многох почтовых программах. А в остальных почтовых программах, где тег <style> поддерживается, не везде поддерживаются медиа-запросы. Надо переделать без медиа-запросов.

Посмотри пример https://codepen.io/Dako/pen/BazQybd

p.s.
Так же рекомендую вместо h2 использовать тег div

2020-10-23 21:51 UTC, vigolajnen commented
Если убирать медиа-запросы, то как менять размеры шрифтов, отступов (на ПК и на мобилке они разные в блоках)?

2020-10-26 08:37 UTC, mailganer commented
Размер шрифтов лучше не менять впринципе, но если и требуется, то да - только через media-запросы. Но работать будет не везде. Сама структура письма должна адаптироваться под мобилку без media-запросов. Это возможно, я приложил пример. Про отступы не понимаю о чём речь. Если будут скриншоты, смогу прокомментировать.

2020-10-28 14:59 UTC, mailganer approved these changes
Принято, молодец!
На будущее всё же замени везде теги h1-h3 на div

2020-10-28 14:59 UTC, merged